version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      - POSTGRES_DB=book_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1337
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin1337@db:5432/book_db
    restart: always

  test:
    build: .
    command: [ "pytest", "tests/" ]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin1337@db:5432/book_db
    volumes:
      - .:/app